add_executable(tinyopt_bench_gtsam sparse.cpp robust_pose.cpp bundle_adjustment.cpp)
add_benchmark_target(tinyopt_bench_gtsam)
if (TARGET gtsam)
  target_link_libraries(tinyopt_bench_gtsam PRIVATE gtsam)
elseif (TARGET GTSAM::gtsam)
  target_link_libraries(tinyopt_bench_gtsam PRIVATE GTSAM::gtsam)
else()
  target_include_directories(tinyopt_bench_gtsam PRIVATE ${GTSAM_INCLUDE_DIR})
  target_link_libraries(tinyopt_bench_gtsam PRIVATE ${GTSAM_LIBRARIES})
endif()