[workspace]
name = "tinyopt"
version = "0.1.0"
description = "A lightweight, header only optimization library"
authors = ["Julien Michot"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[dependencies]
eigen = ">=3.4.0"
cmake = ">=3.25"
ninja = ">=1.10"
compilers = ">=1.0"

# Features

[feature.docs.dependencies]
python = ">=3.9"
sphinx = ">=4.5.0"
breathe = ">=4.34.0"
sphinx-rtd-theme = ">=1.0.0"
doxygen = ">=1.18.0"
myst-parser = ">=2.0.0"
catch2 = ">=3.0.1"

[feature.tests.dependencies]
catch2 = ">=3.0.1"

[feature.sophus.dependencies]
sophus = ">=22.10.2"

[feature.ceres.dependencies]
ceres-solver = ">=2.2.0"
openmp = "*"  # let's make sure openmp is on

[feature.benchmarks.dependencies]
catch2 = ">=3.0.1"
ceres-solver = ">=2.2.0"

[feature.fmt.dependencies]
fmt = ">=8.1.1"
clang-format = ">=18.0.0"
pre-commit = ">=3.7.0"

# --- Environments ---
# This tells Pixi which features to bundle together.
[environments]
default = ["tests"]
all = [ "sophus", "ceres"]
test = ["tests", "sophus"]
bench = ["benchmarks"]
test-ceres = ["tests", "sophus", "ceres"]
bench-ceres = ["benchmarks", "ceres"]
docs = ["docs"]
fmt =["fmt"]

[tasks]
# Base commands
clean = "rm -fr build"

configure = {cmd = "cmake -B build -G Ninja", depends-on = ["clean"]}
configure17 = {cmd = "cmake -B build -G Ninja -DCMAKE_CXX_STANDARD=17", depends-on = ["clean"]}
configure-tests = {cmd = "cmake -B build -G Ninja -DTINYOPT_BUILD_TESTS=ON", depends-on = ["clean"], default-environment = "test" }
configure-bench = {cmd = "cmake -B build -G Ninja -DTINYOPT_BUILD_BENCHMARKS=ON", depends-on = ["clean"], default-environment = "bench" }
configure-pkg = {cmd = "cmake -B build -G Ninja -DTINYOPT_BUILD_TESTS=OFF -DTINYOPT_BUILD_PACKAGES=ON", depends-on = ["clean"], default-environment = "default"}
configure-docs = { cmd = "cmake -B build -G Ninja -DTINYOPT_BUILD_DOCS=ON", depends-on = ["clean"], default-environment = "docs" }

build = { cmd = "cmake --build build", default-environment = "test" }

# formatting
format = { cmd = "./scripts/format.sh", default-environment = "fmt" }
format-check = { cmd = "./scripts/format.sh --check", default-environment = "fmt" }

# test
build-tests = { cmd = "cmake --build build", depends-on = ["configure-tests"], default-environment = "test" }
tests = { cmd = "cd build && ctest --output-on-failure --verbose", depends-on = ["build-tests"], default-environment = "test" }

# benchmarks
build-benchmarks = { cmd = "pixi run build --target run_all_benchmarks", depends-on = ["configure-bench"]}
bench = { cmd = "./build/benchmarks/run_all_benchmarks", depends-on = ["build-benchmarks"] }

# docs
build-docs = { cmd = "cmake --build build --target docs", depends-on = ["configure-docs"], default-environment = "docs" }

# Packages
build-pkg = { cmd = "pixi run build --target deb --target src", depends-on = ["configure-pkg"]}

# CI validation
ci-check = { cmd = "pixi run format-check && pixi run tests && pixi run build-docs", default-environment = "default" }

# Thrid parties builds
build-liepp = "cmake -B build -G Ninja -DTINYOPT_BUILD_LIEPLUSPLUS_TEST=ON && cmake --build build --target tinyopt_test_lie++"
