add_executable(tinyopt_example_c_quadratic quadratic.c)
target_link_libraries(tinyopt_example_c_quadratic PRIVATE tinyopt_c)
set_target_properties(tinyopt_example_c_quadratic PROPERTIES LINKER_LANGUAGE CXX)

add_executable(tinyopt_example_c_fixed_circle_fit fixed_circle_fit.c)
target_link_libraries(tinyopt_example_c_fixed_circle_fit PRIVATE tinyopt_c)
set_target_properties(tinyopt_example_c_fixed_circle_fit PROPERTIES LINKER_LANGUAGE CXX)

add_executable(tinyopt_example_c_dynamic_cost dynamic_cost.c)
target_link_libraries(tinyopt_example_c_dynamic_cost PRIVATE tinyopt_c)
set_target_properties(tinyopt_example_c_dynamic_cost PROPERTIES LINKER_LANGUAGE CXX)

add_executable(tinyopt_example_c_manual_gradient manual_gradient.c)
target_link_libraries(tinyopt_example_c_manual_gradient PRIVATE tinyopt_c)
set_target_properties(tinyopt_example_c_manual_gradient PROPERTIES LINKER_LANGUAGE CXX)

add_executable(tinyopt_example_c_manual_hessian manual_hessian.c)
target_link_libraries(tinyopt_example_c_manual_hessian PRIVATE tinyopt_c)
set_target_properties(tinyopt_example_c_manual_hessian PROPERTIES LINKER_LANGUAGE CXX)