// Copyright 2026 Julien Michot.
// SPDX-License-Identifier: Apache-2.0

#include <array>
#include <iostream>
#include <type_traits>

// Estimate a pinhole camera's focal length and principal point from known 3D/2D
// correspondences. This simple camera model does not include lens distortion.
#include <tinyopt/optimizers/gn.h>

// Tinyopt supplies Eigen aliases, Options, and the Gauss-Newton optimizer API.
using namespace tinyopt;

int main() {
  // Known scene points are paired with image coordinates generated by f=600, cx=320, cy=240.
  const std::array<Vec3, 4> points{Vec3(-1.0, -0.5, 3.0), Vec3(0.8, -0.3, 2.5),
                                   Vec3(-0.4, 0.9, 4.0), Vec3(1.2, 0.7, 3.5)};
  const std::array<Vec2, 4> image_points{Vec2(120.0, 140.0), Vec2(512.0, 168.0), Vec2(260.0, 375.0),
                                         Vec2(525.714286, 360.0)};
  // The three optimized values are focal length and the horizontal/vertical principal point.
  Vec3 camera(650.0, 280.0, 200.0);

  // Return eight reprojection residuals: two image-coordinate errors per correspondence.
  // The generic scalar type lets Tinyopt evaluate the same model with autodiff Jets.
  const auto residuals = [&](const auto& parameters) {
    using Scalar = typename std::decay_t<decltype(parameters)>::Scalar;
    Eigen::Matrix<Scalar, 8, 1> result;
    for (Index i = 0; i < 4; ++i) {
      const auto& point = points[static_cast<std::size_t>(i)];
      result[2 * i] = parameters[0] * point.x() / point.z() + parameters[1] - image_points[i].x();
      result[2 * i + 1] =
          parameters[0] * point.y() / point.z() + parameters[2] - image_points[i].y();
    }
    return result;
  };

  // Disable iteration logging so the example prints only the fitted calibration.
  Options options;
  options.log.enable = false;
  // Gauss-Newton builds a local least-squares model and solves its normal equations.
  // Mat3 is the fixed-size Hessian type for the three camera parameters.
  const auto summary = gn::Optimizer<Mat3>(options)(camera, residuals);
  std::cout << "Estimated [focal length, principal x, principal y]: " << camera.transpose() << '\n'
            << "Optimization succeeded: " << std::boolalpha << summary.Succeeded() << '\n';
  // Use the summary status as the process exit code for scripts and tutorials.
  return summary.Succeeded() ? 0 : 1;
}