add_executable(tinyopt_profiling_1d one_dimensional.cpp)
target_link_libraries(tinyopt_profiling_1d PRIVATE tinyopt)

add_executable(tinyopt_profiling_2d two_dimensional.cpp)
target_link_libraries(tinyopt_profiling_2d PRIVATE tinyopt)

add_executable(tinyopt_profiling_sparse_ba sparse_bundle_adjustment.cpp)
target_link_libraries(tinyopt_profiling_sparse_ba PRIVATE tinyopt)

target_include_directories(tinyopt_profiling_1d PRIVATE ${PROJECT_SOURCE_DIR}/benchmarks/common)
target_include_directories(tinyopt_profiling_2d PRIVATE ${PROJECT_SOURCE_DIR}/benchmarks/common)
target_include_directories(tinyopt_profiling_sparse_ba
  PRIVATE ${PROJECT_SOURCE_DIR}/benchmarks/common)