name: Tinyopt Build & Tests
run-name: Tinyopt Builds
on: [push]
jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Packages
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.sh
          vcpkg integrate install
          cd ..

      - name: Install Catch2
        run: |
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          cmake -B build -S. -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release
          cmake --build build/ --config Release --target install

      - name: Pip install Sphinx and Breathe
        run: |
          pip install "sphinx<8" "breathe>=4.35" "sphinx-rtd-theme>=1.0" "myst-parser>=2.0"

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX -DTINYOPT_BUILD_TESTS=OFF -DTINYOPT_BUILD_DOCS=ON -DTINYOPT_BUILD_PACKAGES=OFF -DTINYOPT_BUILD_PIP_PACKAGE=OFF

      - name: Build & Install Tinyopt
        run: |-
          cmake --build build --target docs
          cmake --build build
          cmake --install build
